# Generated by Django 4.1.4 on 2022-12-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_status_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(default='nothing is specified'),
        ),
    ]
